import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { Report } from '../types';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Modal } from '../components/ui/Modal';
import { formatDate } from '../lib/utils';
import {
  FileText,
  Plus,
  Printer,
  Eye,
} from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const [reports, setReports] = useState<Report[]>([]);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [isGenerateModalOpen, setIsGenerateModalOpen] = useState(false);
  const [reportType, setReportType] = useState('BLUF');
  const [reportTitle, setReportTitle] = useState('Tactical Commander Threat Briefing');
  const [incidentId, setIncidentId] = useState('INC-001');
  const [notes, setNotes] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const fetchReports = async () => {
    try {
      const data = await api.getReports();
      setReports(data);
    } catch (err) {
      console.error('Failed to load reports:', err);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);
    try {
      const rep = await api.generateReport({
        title: reportTitle,
        report_type: reportType,
        incident_id: incidentId || undefined,
        notes: notes || undefined,
      });
      setIsGenerateModalOpen(false);
      fetchReports();
      setSelectedReport(rep);
    } catch (err: any) {
      alert(`Report generation error: ${err.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePrint = (report: Report) => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${report.title} - Clarion</title>
            <style>
              body { background: #ffffff; color: #000000; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 24px; }
              @media print { body { padding: 0; } }
            </style>
          </head>
          <body>${report.content_html}</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-extrabold font-mono tracking-tight text-slate-900 dark:text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600 dark:text-cyan-400" />
            OPERATIONAL REPORTING & COMMANDER BRIEFS
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 font-sans mt-0.5">
            Generates standardized military BLUF briefs, technical dossiers, and daily threat posture reports.
          </p>
        </div>

        <Button variant="primary" size="sm" onClick={() => setIsGenerateModalOpen(true)}>
          <Plus className="w-4 h-4 mr-1" />
          Generate New Report
        </Button>
      </div>

      {/* Reports Table */}
      <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0b1329] shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs font-sans">
            <thead>
              <tr className="bg-slate-50 dark:bg-slate-900/90 border-b border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 font-mono text-[11px] uppercase tracking-wider">
                <th className="p-3.5 pl-5">Report ID</th>
                <th className="p-3.5">Title</th>
                <th className="p-3.5">Type</th>
                <th className="p-3.5">Linked Incident</th>
                <th className="p-3.5">Generated By</th>
                <th className="p-3.5">Date (UTC)</th>
                <th className="p-3.5 pr-5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 dark:divide-slate-800/60">
              {reports.map((rep) => (
                <tr key={rep.id} className="hover:bg-slate-50 dark:hover:bg-slate-900/60 transition-colors">
                  <td className="p-3.5 pl-5 font-mono text-blue-600 dark:text-cyan-400 font-bold">{rep.id}</td>
                  <td className="p-3.5 font-semibold text-slate-900 dark:text-slate-200">{rep.title}</td>
                  <td className="p-3.5">
                    <span className="px-2 py-0.5 rounded-full bg-blue-50 dark:bg-cyan-950/60 border border-blue-200 dark:border-cyan-800/50 text-blue-700 dark:text-cyan-300 font-mono text-[10px] uppercase font-bold">
                      {rep.report_type}
                    </span>
                  </td>
                  <td className="p-3.5 font-mono text-slate-700 dark:text-slate-300">{rep.incident_id || 'Global'}</td>
                  <td className="p-3.5 font-mono text-slate-500 dark:text-slate-400 text-[11px]">{rep.generated_by}</td>
                  <td className="p-3.5 font-mono text-slate-500 dark:text-slate-400">{formatDate(rep.created_at)}</td>
                  <td className="p-3.5 pr-5 text-right space-x-2">
                    <Button variant="secondary" size="sm" onClick={() => setSelectedReport(rep)}>
                      <Eye className="w-3.5 h-3.5 mr-1 text-blue-600 dark:text-cyan-400" />
                      Preview
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => handlePrint(rep)}>
                      <Printer className="w-3.5 h-3.5 mr-1" />
                      Print / PDF
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal: Preview Report */}
      <Modal
        isOpen={!!selectedReport}
        onClose={() => setSelectedReport(null)}
        title={`Report Preview: ${selectedReport?.title}`}
        maxWidth="max-w-4xl"
      >
        {selectedReport && (
          <div className="space-y-4">
            <div className="bg-white text-slate-900 p-6 rounded-xl border border-slate-200 shadow-inner max-h-[60vh] overflow-y-auto">
              <div dangerouslySetInnerHTML={{ __html: selectedReport.content_html }} />
            </div>

            <div className="flex justify-end gap-2 pt-2 border-t border-slate-200 dark:border-slate-800">
              <Button variant="outline" size="sm" onClick={() => setSelectedReport(null)}>
                Close
              </Button>
              <Button variant="primary" size="sm" onClick={() => handlePrint(selectedReport)}>
                <Printer className="w-4 h-4 mr-1.5" />
                Print / Save as PDF
              </Button>
            </div>
          </div>
        )}
      </Modal>

      {/* Modal: Generate New Report */}
      <Modal
        isOpen={isGenerateModalOpen}
        onClose={() => setIsGenerateModalOpen(false)}
        title="Generate Operational Defense Report"
      >
        <form onSubmit={handleGenerate} className="space-y-4 text-xs font-sans">
          <div>
            <label className="block text-slate-600 dark:text-slate-400 font-mono text-[11px] mb-1 font-semibold">REPORT TYPE</label>
            <select
              value={reportType}
              onChange={(e) => {
                setReportType(e.target.value);
                if (e.target.value === 'DAILY_SUMMARY') setReportTitle('Daily Threat Activity & Defense Posture');
                else if (e.target.value === 'BLUF') setReportTitle('Commander BLUF Threat Briefing');
                else if (e.target.value === 'INCIDENT') setReportTitle('Security Incident Technical Dossier');
              }}
              className="w-full bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg p-2 text-slate-900 dark:text-slate-100 font-mono focus:bg-white"
            >
              <option value="BLUF">Commander BLUF Summary</option>
              <option value="INCIDENT">Incident Technical Dossier</option>
              <option value="DAILY_SUMMARY">Daily Threat Posture Summary</option>
              <option value="MITRE_SUMMARY">MITRE ATT&CK Coverage Summary</option>
              <option value="ANALYST_INVESTIGATION">Analyst Investigation Dossier</option>
            </select>
          </div>

          <div>
            <label className="block text-slate-600 dark:text-slate-400 font-mono text-[11px] mb-1 font-semibold">REPORT TITLE</label>
            <input
              type="text"
              value={reportTitle}
              onChange={(e) => setReportTitle(e.target.value)}
              className="w-full bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg p-2 text-slate-900 dark:text-slate-100 font-sans focus:bg-white"
              required
            />
          </div>

          {(reportType === 'BLUF' || reportType === 'INCIDENT') && (
            <div>
              <label className="block text-slate-600 dark:text-slate-400 font-mono text-[11px] mb-1 font-semibold">TARGET INCIDENT ID</label>
              <input
                type="text"
                value={incidentId}
                onChange={(e) => setIncidentId(e.target.value)}
                className="w-full bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg p-2 text-slate-900 dark:text-slate-100 font-mono focus:bg-white"
                required
              />
            </div>
          )}

          <div>
            <label className="block text-slate-600 dark:text-slate-400 font-mono text-[11px] mb-1 font-semibold">ADDITIONAL ANALYST DIRECTIVES / NOTES</label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              placeholder="Provide special containment directions or commander mandates..."
              className="w-full bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg p-2 text-slate-900 dark:text-slate-100 font-sans focus:bg-white"
            />
          </div>

          <div className="flex justify-end gap-2 pt-2">
            <Button type="button" variant="outline" size="sm" onClick={() => setIsGenerateModalOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" variant="primary" size="sm" isLoading={isGenerating}>
              Generate Report
            </Button>
          </div>
        </form>
      </Modal>
    </div>
  );
};
