import React from 'react';
import { Sparkles, Bot, CheckCircle2, RefreshCw } from 'lucide-react';
import { Button } from './ui/Button';

interface BlufCardProps {
  blufText?: string | null;
  onRegenerate?: () => void;
  isLoading?: boolean;
  aiProviderName?: string;
}

export const BlufCard: React.FC<BlufCardProps> = ({
  blufText,
  onRegenerate,
  isLoading = false,
  aiProviderName = 'DEMO AI (Deterministic Fallback)',
}) => {
  return (
    <div className="bg-gradient-to-br from-blue-50/80 via-white to-slate-50 dark:from-[#0c1833] dark:to-[#070e20] border-2 border-blue-200 dark:border-cyan-500/40 rounded-2xl p-6 shadow-sm dark:shadow-xl relative overflow-hidden">
      {/* Decorative ambient accent */}
      <div className="absolute top-0 right-0 w-48 h-48 bg-blue-400/5 dark:bg-cyan-500/5 rounded-full blur-3xl pointer-events-none" />

      <div className="flex flex-wrap items-center justify-between gap-3 mb-5 border-b border-blue-200 dark:border-cyan-900/40 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-blue-100 dark:bg-cyan-950 border border-blue-300 dark:border-cyan-500/60 flex items-center justify-center text-blue-700 dark:text-cyan-400 shadow-sm">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold font-mono tracking-wide text-slate-900 dark:text-slate-100 flex items-center gap-2">
              COMMANDER BLUF BRIEFING
              <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded-full bg-blue-100 dark:bg-cyan-950 text-blue-800 dark:text-cyan-300 border border-blue-200 dark:border-cyan-500/40 font-bold">
                Bottom Line Up Front
              </span>
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 font-sans">
              Structured operational intelligence summary generated by {aiProviderName}
            </p>
          </div>
        </div>

        {onRegenerate && (
          <Button
            variant="outline"
            size="sm"
            onClick={onRegenerate}
            isLoading={isLoading}
            className="border-blue-300 text-blue-700 hover:bg-blue-50 dark:border-cyan-500/40 dark:text-cyan-300 dark:hover:bg-cyan-950/50"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Regenerate BLUF
          </Button>
        )}
      </div>

      {blufText ? (
        <div className="text-sm leading-relaxed text-slate-800 dark:text-slate-200 font-sans space-y-4 whitespace-pre-line bg-white dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800/80 p-5 rounded-xl shadow-sm">
          {blufText}
        </div>
      ) : (
        <div className="text-center py-8 bg-white/60 dark:bg-slate-950/40 border border-dashed border-slate-300 dark:border-slate-800 rounded-xl">
          <Bot className="w-8 h-8 text-slate-400 dark:text-slate-500 mx-auto mb-2" />
          <p className="text-xs font-mono text-slate-500 dark:text-slate-400 mb-3">
            No BLUF assessment generated yet for this incident.
          </p>
          {onRegenerate && (
            <Button variant="primary" size="sm" onClick={onRegenerate} isLoading={isLoading}>
              <Sparkles className="w-4 h-4 mr-1.5" />
              Generate Commander BLUF
            </Button>
          )}
        </div>
      )}

      {/* Footer reassurance */}
      <div className="mt-4 flex items-center justify-between text-[11px] font-mono text-slate-500 dark:text-slate-400">
        <span className="flex items-center gap-1">
          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
          Grounded in corroborated multi-INT sensor feeds
        </span>
        <span className="text-blue-600 dark:text-cyan-400/80 font-semibold">ICD-203 Standard Vocabulary</span>
      </div>
    </div>
  );
};
